export { JulmaFormComponent } from './julma-form/julma-form.component';
export { JulmaComponent } from './julma/julma.component';
export { JulmaRegisterComponent } from './julma-register/julma-register.component'
export { DashBoardComponent } from './dash-board/dash-board.component';
export { OrdersComponent } from './orders/orders.component';
export { ProductsComponent } from './products/products.component';
export { CustomersComponent } from './customers/customers.component';
export { ReportsComponent } from './reports/reports.component';
export { WalletComponent } from './wallet/wallet.component';
export { ReviewsComponent } from './reviews/reviews.component';
export { OffersComponent } from './offers/offers.component';
export { ActiveOffersDetalisComponent } from './offers/offers-child-components/active-offers-detalis/active-offers-detalis.component';
export { ActivePreviousOffersComponent } from './offers/offers-child-components/active-previous-offers/active-previous-offers.component'
export { HelpUsComponent } from './help-us/help-us.component';
export { SettingsComponent } from './settings/settings.component';
export { ChatComponent } from './chat/chat.component';
export { NotificationComponent } from './notification/notification.component';
export { ReportCustomersComponent } from './reports/report-child-components/report-customers/report-customers.component';
export { ReportProductsComponent } from './reports/report-child-components/report-products/report-products.component';
export { ReportSalesComponent } from './reports/report-child-components/report-sales/report-sales.component';
export { ReportVisitorsComponent } from './reports/report-child-components/report-visitors/report-visitors.component';
